from nurses_2.colors import Color, color_pair, BLACK, BLUE, WHITE, BLACK_ON_BLACK

GRAY = Color(25, 25, 25)

TETRIS_APP_BACKGROUND_COLOR = BLACK_ON_BLACK
HELD_BORDER_COLOR = color_pair(WHITE, BLUE)
NEXT_BORDER_COLOR = color_pair(WHITE, BLUE)
MATRIX_BACKGROUND_COLOR = color_pair(GRAY, GRAY)
HELD_BACKGROUND_COLOR = BLACK_ON_BLACK
NEXT_BACKGROUND_COLOR = BLACK_ON_BLACK
CLEAR_LINE_FLASH_COLOR = color_pair(BLACK, WHITE)
