from nurses_2.colors import (
    RED,
    BLUE,
    GREEN,
    YELLOW,
    CYAN,
    BLACK,
    WHITE,
    BLACK_ON_BLACK,
    WHITE_ON_BLACK,
    Color,
    color_pair,
)

GRAY = Color(25, 25, 25)
PURPLE = Color.from_hex("#800080")
ORANGE = Color.from_hex("#FF7F00")

WHITE_ON_BLUE = color_pair(WHITE, BLUE)
GRAY_ON_GRAY = color_pair(GRAY, GRAY)

TETRIS_APP_BACKGROUND_COLOR = BLACK_ON_BLACK
HELD_BORDER_COLOR = WHITE_ON_BLUE
NEXT_BORDER_COLOR = WHITE_ON_BLUE
MATRIX_BACKGROUND_COLOR = GRAY_ON_GRAY
HELD_BACKGROUND_COLOR = BLACK_ON_BLACK
NEXT_BACKGROUND_COLOR = BLACK_ON_BLACK
CLEAR_LINE_FLASH_COLOR = WHITE_ON_BLACK

J_COLOR = BLUE
L_COLOR = ORANGE
S_COLOR = GREEN
T_COLOR = PURPLE
Z_COLOR = RED
I_COLOR = CYAN
O_COLOR = YELLOW
