"""Keyboard special keys."""
from enum import Enum


class Key(str, Enum):
    """Special keys."""

    Escape = "escape"
    Left = "left"
    Right = "right"
    Up = "up"
    Down = "down"
    Home = "home"
    End = "end"
    Insert = "insert"
    Delete = "delete"
    PageUp = "pageup"
    PageDown = "pagedown"
    F1 = "f1"
    F2 = "f2"
    F3 = "f3"
    F4 = "f4"
    F5 = "f5"
    F6 = "f6"
    F7 = "f7"
    F8 = "f8"
    F9 = "f9"
    F10 = "f10"
    F11 = "f11"
    F12 = "f12"
    F13 = "f13"
    F14 = "f14"
    F15 = "f15"
    F16 = "f16"
    F17 = "f17"
    F18 = "f18"
    F19 = "f19"
    F20 = "f20"
    F21 = "f21"
    F22 = "f22"
    F23 = "f23"
    F24 = "f24"
    ScrollUp = "<scroll-up>"
    ScrollDown = "<scroll-down>"
    Paste = "<paste>"
    Ignore = "<ignore>"
    Tab = "tab"
    Enter = "enter"
    Backspace = "backspace"
