BAD_FLAG    = "✗"
BOMB        = "💣"
COOL        = "😎"
EXPLODED    = "💥"
FLAG        = "⚑"
HAPPY       = "😀"
KNOCKED_OUT = "😵"
SURPRISED   = "😮"

LIGHT_BOX   = "─│┌┬┐└┴┘├┼┤"
HEAVY_BOX   = "━┃┏┳┓┗┻┛┣╋┫"
