from nurses_2.colors import RED, YELLOW, WHITE, GREEN, BLUE, Color

FRONT_COLOR  = RED
BACK_COLOR   = ORANGE = Color.from_hex("f46e07")
TOP_COLOR    = GREEN
BOTTOM_COLOR = BLUE
RIGHT_COLOR  = WHITE
LEFT_COLOR   = YELLOW

FACE_COLORS = (
    FRONT_COLOR,
    BACK_COLOR,
    TOP_COLOR,
    BOTTOM_COLOR,
    RIGHT_COLOR,
    LEFT_COLOR,
)
