# include "vt500_parser.h"

typedef unsigned char state_change_t;

state_change_t STATE_TABLE[14][256] = {
    {
        /* CSI_ENTRY = 0 */
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        PARAM | (CSI_PARAM << 4),
        0 | (CSI_IGNORE << 4),
        PARAM | (CSI_PARAM << 4),
        COLLECT | (CSI_PARAM << 4),
        COLLECT | (CSI_PARAM << 4),
        COLLECT | (CSI_PARAM << 4),
        COLLECT | (CSI_PARAM << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* CSI_IGNORE = 1 */
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        0 | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* CSI_INTERMEDIATE = 2 */
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* CSI_PARAM = 3 */
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        COLLECT | (CSI_INTERMEDIATE << 4),
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        0 | (CSI_IGNORE << 4),
        PARAM | 0,
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        0 | (CSI_IGNORE << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        CSI_DISPATCH | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* DCS_ENTRY = 4 */
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        PARAM | (DCS_PARAM << 4),
        0 | (DCS_IGNORE << 4),
        PARAM | (DCS_PARAM << 4),
        COLLECT | (DCS_PARAM << 4),
        COLLECT | (DCS_PARAM << 4),
        COLLECT | (DCS_PARAM << 4),
        COLLECT | (DCS_PARAM << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* DCS_IGNORE = 5 */
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* DCS_INTERMEDIATE = 6 */
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* DCS_PARAM = 7 */
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        COLLECT | (DCS_INTERMEDIATE << 4),
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        PARAM | 0,
        0 | (DCS_IGNORE << 4),
        PARAM | 0,
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_IGNORE << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        0 | (DCS_PASSTHROUGH << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* DCS_PASSTHROUGH = 8 */
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        EXECUTE | (GROUND << 4),
        PUT | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        PUT | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* ESCAPE = 9 */
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        COLLECT | (ESCAPE_INTERMEDIATE << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        ESC_DISPATCH | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* ESCAPE_INTERMEDIATE = 10 */
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        COLLECT | 0,
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        ESC_DISPATCH | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* GROUND = 11 */
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        EXECUTE | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        PRINT | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* OSC_STRING = 12 */
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        OSC_PUT | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
    {
        /* SOS_PM_APC_STRING = 13 */
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        0 | (ESCAPE << 4),
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        IGNORE | 0,
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (DCS_ENTRY << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (SOS_PM_APC_STRING << 4),
        EXECUTE | (GROUND << 4),
        EXECUTE | (GROUND << 4),
        0 | (CSI_ENTRY << 4),
        0 | (GROUND << 4),
        0 | (OSC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
        0 | (SOS_PM_APC_STRING << 4),
    },
};

action_t ENTRY_ACTIONS[] = {
    CLEAR, /* CSI_ENTRY */
    0,
    0,
    0,
    CLEAR, /* DCS_ENTRY */
    0,
    0,
    0,
    HOOK, /* DCS_PASSTHROUGH */
    CLEAR, /* ESCAPE */
    0,
    0,
    OSC_START, /* OSC_STRING */
    0,
};

action_t EXIT_ACTIONS[] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    UNHOOK, /* DCS_PASSTHROUGH */
    0,
    0,
    0,
    OSC_END, /* OSC_STRING */
    0,
};

static void do_action(vtparse *parser, action_t action, unsigned int ch){
    switch(action) {
        case PRINT:
        case EXECUTE:
        case HOOK:
        case PUT:
        case OSC_START:
        case OSC_PUT:
        case OSC_END:
        case UNHOOK:
        case CSI_DISPATCH:
        case ESC_DISPATCH:
            parser->callback(parser, action, ch);
            break;
        case IGNORE:
            break;
        case COLLECT:
        {
            if(parser->intermediate_chars_len + 1 > MAX_INTERMEDIATE_CHARS)
                parser->ignore_flagged = 1;
            else
                parser->intermediate_chars[parser->intermediate_chars_len++] = (unsigned char)ch;
            break;
        }
        case PARAM:
        {
            if(ch == ';') {
                parser->params_len += 1;
                if (parser->params_len > MAX_PARAMS) {
                     parser->callback(parser, ERROR, 0);
                     break;
                }
                parser->params[parser->params_len - 1] = 0;
            } else {
                int current_param;
                if(parser->params_len == 0) {
                    parser->params_len = 1;
                    parser->params[0] = 0;
                }
                current_param = parser->params_len - 1;
                parser->params[current_param] *= 10;
                parser->params[current_param] += ch - '0';
            }
            break;
        }
        case CLEAR:
            parser->intermediate_chars_len = 0;
            parser->params_len = 0;
            parser->ignore_flagged = 0;
            break;
        default:
            parser->callback(parser, ERROR, 0);
    }
}

static void do_state_change(vtparse *parser, state_change_t state_change, unsigned int ch){
    state_t new_state = STATE(state_change);
    action_t action = ACTION(state_change);

    if(new_state) {
        action_t exit_action = EXIT_ACTIONS[parser->state-1];
        action_t entry_action = ENTRY_ACTIONS[new_state-1];
        if(exit_action) do_action(parser, exit_action, 0);
        if(action) do_action(parser, action, ch);
        if(entry_action)do_action(parser, entry_action, 0);
        parser->state = new_state;
    } else {
        do_action(parser, action, ch);
    }
}

static void feed1(vtparse *parser, unsigned int ch){
    if(parser->utf8_char_bytes != 1) {
        parser->utf8_char = (parser->utf8_char << 6) | (ch & 0x3F);
        parser->utf8_char_bytes--;
        if(parser->utf8_char_bytes == 1) do_state_change(parser, PRINT, parser->utf8_char);
    } else if(ch & 0x80) {
        int bit = 6;
        do {
            if((ch & (1<<bit)) == 0) break;
            bit--;
        } while(bit > 1);
        parser->utf8_char = 0;
        parser->utf8_char_bytes = 7 - bit;
        switch(parser->utf8_char_bytes) {
            case 2:
                parser->utf8_char = ch & 0x1f;
                break;
            case 3:
                parser->utf8_char = ch & 0xf;
                break;
            case 4:
                parser->utf8_char = ch & 0x7;
                break;
            case 5:
                parser->utf8_char = ch & 0x3;
                break;
            case 6:
                parser->utf8_char = ch & 0x1;
                break;
        }
    } else {
        state_change_t state_change = STATE_TABLE[parser->state-1][ch];
        do_state_change(parser, state_change, ch);
    }
}
