from .mouse_data_structures import *

LEFT = MouseButton.LEFT
MIDDLE = MouseButton.MIDDLE
RIGHT = MouseButton.RIGHT
NO_BUTTON = MouseButton.NO_BUTTON
UNKNOWN_BUTTON = MouseButton.UNKNOWN_BUTTON

MOUSE_UP = MouseEventType.MOUSE_UP
MOUSE_DOWN = MouseEventType.MOUSE_DOWN
MOUSE_MOVE = MouseEventType.MOUSE_MOVE
SCROLL_UP = MouseEventType.SCROLL_UP
SCROLL_DOWN = MouseEventType.SCROLL_DOWN

NO_MODIFIER = MouseModifier.NO_MODIFIER
SHIFT = MouseModifier.SHIFT
ALT = MouseModifier.ALT
SHIFT_ALT = MouseModifier.SHIFT_ALT
CONTROL = MouseModifier.CONTROL
SHIFT_CONTROL = MouseModifier.SHIFT_CONTROL
ALT_CONTROL = MouseModifier.ALT_CONTROL
SHIFT_ALT_CONTROL = MouseModifier.SHIFT_ALT_CONTROL
UNKNOWN_MODIFIER = MouseModifier.UNKNOWN_MODIFIER

TERM_SGR = {
    ( 0, "m"): (MOUSE_UP, LEFT, NO_MODIFIER),
    ( 4, "m"): (MOUSE_UP, LEFT, SHIFT),
    ( 8, "m"): (MOUSE_UP, LEFT, ALT),
    (12, "m"): (MOUSE_UP, LEFT, SHIFT_ALT),
    (16, "m"): (MOUSE_UP, LEFT, CONTROL),
    (20, "m"): (MOUSE_UP, LEFT, SHIFT_CONTROL),
    (24, "m"): (MOUSE_UP, LEFT, ALT_CONTROL),
    (28, "m"): (MOUSE_UP, LEFT, SHIFT_ALT_CONTROL),

    ( 1, "m"): (MOUSE_UP, MIDDLE, NO_MODIFIER),
    ( 5, "m"): (MOUSE_UP, MIDDLE, SHIFT),
    ( 9, "m"): (MOUSE_UP, MIDDLE, ALT),
    (13, "m"): (MOUSE_UP, MIDDLE, SHIFT_ALT),
    (17, "m"): (MOUSE_UP, MIDDLE, CONTROL),
    (21, "m"): (MOUSE_UP, MIDDLE, SHIFT_CONTROL),
    (25, "m"): (MOUSE_UP, MIDDLE, ALT_CONTROL),
    (29, "m"): (MOUSE_UP, MIDDLE, SHIFT_ALT_CONTROL),

    ( 2, "m"): (MOUSE_UP, RIGHT, NO_MODIFIER),
    ( 6, "m"): (MOUSE_UP, RIGHT, SHIFT),
    (10, "m"): (MOUSE_UP, RIGHT, ALT),
    (14, "m"): (MOUSE_UP, RIGHT, SHIFT_ALT),
    (18, "m"): (MOUSE_UP, RIGHT, CONTROL),
    (22, "m"): (MOUSE_UP, RIGHT, SHIFT_CONTROL),
    (26, "m"): (MOUSE_UP, RIGHT, ALT_CONTROL),
    (30, "m"): (MOUSE_UP, RIGHT, SHIFT_ALT_CONTROL),

    ( 0, "M"): (MOUSE_DOWN, LEFT, NO_MODIFIER),
    ( 4, "M"): (MOUSE_DOWN, LEFT, SHIFT),
    ( 8, "M"): (MOUSE_DOWN, LEFT, ALT),
    (12, "M"): (MOUSE_DOWN, LEFT, SHIFT_ALT),
    (16, "M"): (MOUSE_DOWN, LEFT, CONTROL),
    (20, "M"): (MOUSE_DOWN, LEFT, SHIFT_CONTROL),
    (24, "M"): (MOUSE_DOWN, LEFT, ALT_CONTROL),
    (28, "M"): (MOUSE_DOWN, LEFT, SHIFT_ALT_CONTROL),

    ( 1, "M"): (MOUSE_DOWN, MIDDLE, NO_MODIFIER),
    ( 5, "M"): (MOUSE_DOWN, MIDDLE, SHIFT),
    ( 9, "M"): (MOUSE_DOWN, MIDDLE, ALT),
    (13, "M"): (MOUSE_DOWN, MIDDLE, SHIFT_ALT),
    (17, "M"): (MOUSE_DOWN, MIDDLE, CONTROL),
    (21, "M"): (MOUSE_DOWN, MIDDLE, SHIFT_CONTROL),
    (25, "M"): (MOUSE_DOWN, MIDDLE, ALT_CONTROL),
    (29, "M"): (MOUSE_DOWN, MIDDLE, SHIFT_ALT_CONTROL),

    ( 2, "M"): (MOUSE_DOWN, RIGHT, NO_MODIFIER),
    ( 6, "M"): (MOUSE_DOWN, RIGHT, SHIFT),
    (10, "M"): (MOUSE_DOWN, RIGHT, ALT),
    (14, "M"): (MOUSE_DOWN, RIGHT, SHIFT_ALT),
    (18, "M"): (MOUSE_DOWN, RIGHT, CONTROL),
    (22, "M"): (MOUSE_DOWN, RIGHT, SHIFT_CONTROL),
    (26, "M"): (MOUSE_DOWN, RIGHT, ALT_CONTROL),
    (30, "M"): (MOUSE_DOWN, RIGHT, SHIFT_ALT_CONTROL),

    (32, "M"): (MOUSE_MOVE, LEFT, NO_MODIFIER),
    (36, "M"): (MOUSE_MOVE, LEFT, SHIFT),
    (40, "M"): (MOUSE_MOVE, LEFT, ALT),
    (44, "M"): (MOUSE_MOVE, LEFT, SHIFT_ALT),
    (48, "M"): (MOUSE_MOVE, LEFT, CONTROL),
    (52, "M"): (MOUSE_MOVE, LEFT, SHIFT_CONTROL),
    (56, "M"): (MOUSE_MOVE, LEFT, ALT_CONTROL),
    (60, "M"): (MOUSE_MOVE, LEFT, SHIFT_ALT_CONTROL),

    (33, "M"): (MOUSE_MOVE, MIDDLE, NO_MODIFIER),
    (37, "M"): (MOUSE_MOVE, MIDDLE, SHIFT),
    (41, "M"): (MOUSE_MOVE, MIDDLE, ALT),
    (45, "M"): (MOUSE_MOVE, MIDDLE, SHIFT_ALT),
    (49, "M"): (MOUSE_MOVE, MIDDLE, CONTROL),
    (53, "M"): (MOUSE_MOVE, MIDDLE, SHIFT_CONTROL),
    (57, "M"): (MOUSE_MOVE, MIDDLE, ALT_CONTROL),
    (61, "M"): (MOUSE_MOVE, MIDDLE, SHIFT_ALT_CONTROL),

    (34, "M"): (MOUSE_MOVE, RIGHT, NO_MODIFIER),
    (38, "M"): (MOUSE_MOVE, RIGHT, SHIFT),
    (42, "M"): (MOUSE_MOVE, RIGHT, ALT),
    (46, "M"): (MOUSE_MOVE, RIGHT, SHIFT_ALT),
    (50, "M"): (MOUSE_MOVE, RIGHT, CONTROL),
    (54, "M"): (MOUSE_MOVE, RIGHT, SHIFT_CONTROL),
    (58, "M"): (MOUSE_MOVE, RIGHT, ALT_CONTROL),
    (62, "M"): (MOUSE_MOVE, RIGHT, SHIFT_ALT_CONTROL),

    (35, "m"): (MOUSE_MOVE, NO_BUTTON, NO_MODIFIER),
    (39, "m"): (MOUSE_MOVE, NO_BUTTON, SHIFT),
    (43, "m"): (MOUSE_MOVE, NO_BUTTON, ALT),
    (47, "m"): (MOUSE_MOVE, NO_BUTTON, SHIFT_ALT),
    (51, "m"): (MOUSE_MOVE, NO_BUTTON, CONTROL),
    (55, "m"): (MOUSE_MOVE, NO_BUTTON, SHIFT_CONTROL),
    (59, "m"): (MOUSE_MOVE, NO_BUTTON, ALT_CONTROL),
    (63, "m"): (MOUSE_MOVE, NO_BUTTON, SHIFT_ALT_CONTROL),

    (64, "M"): (SCROLL_UP, NO_BUTTON, NO_MODIFIER),
    (68, "M"): (SCROLL_UP, NO_BUTTON, SHIFT),
    (72, "M"): (SCROLL_UP, NO_BUTTON, ALT),
    (76, "M"): (SCROLL_UP, NO_BUTTON, SHIFT_ALT),
    (80, "M"): (SCROLL_UP, NO_BUTTON, CONTROL),
    (84, "M"): (SCROLL_UP, NO_BUTTON, SHIFT_CONTROL),
    (88, "M"): (SCROLL_UP, NO_BUTTON, ALT_CONTROL),
    (92, "M"): (SCROLL_UP, NO_BUTTON, SHIFT_ALT_CONTROL),

    (65, "M"): (SCROLL_DOWN, NO_BUTTON, NO_MODIFIER),
    (69, "M"): (SCROLL_DOWN, NO_BUTTON, SHIFT),
    (73, "M"): (SCROLL_DOWN, NO_BUTTON, ALT),
    (77, "M"): (SCROLL_DOWN, NO_BUTTON, SHIFT_ALT),
    (81, "M"): (SCROLL_DOWN, NO_BUTTON, CONTROL),
    (85, "M"): (SCROLL_DOWN, NO_BUTTON, SHIFT_CONTROL),
    (89, "M"): (SCROLL_DOWN, NO_BUTTON, ALT_CONTROL),
    (93, "M"): (SCROLL_DOWN, NO_BUTTON, SHIFT_ALT_CONTROL),
}

TYPICAL = {
    32: (MOUSE_DOWN, LEFT, UNKNOWN_MODIFIER),
    33: (MOUSE_DOWN, MIDDLE, UNKNOWN_MODIFIER),
    34: (MOUSE_DOWN, RIGHT, UNKNOWN_MODIFIER),
    35: (MOUSE_UP, UNKNOWN_BUTTON,  UNKNOWN_MODIFIER),

    64: (MOUSE_MOVE, LEFT, UNKNOWN_MODIFIER),
    65: (MOUSE_MOVE, MIDDLE, UNKNOWN_MODIFIER),
    66: (MOUSE_MOVE, RIGHT, UNKNOWN_MODIFIER),
    67: (MOUSE_MOVE, NO_BUTTON, UNKNOWN_MODIFIER),

    96: (SCROLL_UP, NO_BUTTON, UNKNOWN_MODIFIER),
    97: (SCROLL_DOWN, NO_BUTTON, UNKNOWN_MODIFIER),
}

URXVT = {
    32: (MOUSE_DOWN, UNKNOWN_BUTTON, UNKNOWN_MODIFIER),
    35: (MOUSE_UP, UNKNOWN_BUTTON, UNKNOWN_MODIFIER),
    96: (SCROLL_UP, NO_BUTTON, UNKNOWN_MODIFIER),
    97: (SCROLL_DOWN, NO_BUTTON, UNKNOWN_MODIFIER),
}